### ISSUE TITLE
Support .ED8?

### ISSUE THREAD

**Issue by makc-ar** [RikuKH3/bblack_transkit#1]
Судя по заголовку это 8 bit текстуры, наверное.  EXODUS_0.ED8, EXODUS_1.ED8 и т.д.
В начале игры идёт их заставка вроде.

**Comment by RikuKH3** [comment]
You can find ED8 and EDT decompression code here:
https://github.com/Ouroboros/Arianrhod/blob/master/Source/sources/Crass-source/cui/A98SYS%20ENGINE/A98SYS%20ENGINE.cpp

**Comment by makc-ar** [comment]
А ты можешь скомпилить? Нужен конверт для локализации .ED8 на русский язык. В версии 1.3 антивирь начал ругаться на патчеры. Хз почему.

**Comment by RikuKH3** [comment]
Added uncompressed ED8 image support into game executable.
